spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/heystudent
    username: postgres
    password: admin123
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: create-drop
    database: postgresql
    show-sql: true
#   activemq:
#     broker-url: tcp://localhost:61616
#     user: admin
#     password: admin
#     packages:
#       trust-all: true
server:
  port: 8080
